[package]
name = "rfc3339"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
description = "A Portable RFC3339 Timestamp Formatter."

[dependencies]
heapless = { version = "0.8.0" }

[features]
default = ["std"]
std = []